"use client";
import { useTranslation } from "react-i18next";

export const useLabels = () => {
  const { t } = useTranslation();

  return {
    home: t("home"),
    advanced_users: t("advanced_users"),
    employee_users: t("employee_users"),
    time_zone: t("time_zone"),
    map: t("map"),
    map_data: t("map_data"),
    add_user: t("add_user"),
    users_data: t("users_data"),
    id: t("id"),
    name: t("name"),
    email: t("email"),
    actions: t("actions"),
    edit: t("edit"),
    save: t("save"),
    delete: t("delete"),
    advanced_users_table: t("advanced_users_table"),
    add_data: t("add_data"),
    edit_all_users: t("edit_all_users"),
    phone: t("phone"),
    address: t("address"),
    date_range: t("date_range"),
    image: t("image"),
    hobby: t("hobby"),
    city: t("city"),
    state: t("state"),
    country: t("country"),
    add_hobby: t("add_hobby"),
    cancel: t("cancel"),
    submit: t("submit"),
    all_edit_users: t("all_edit_users"),
    add_row: t("add_row"),
    start_time: t("start_time"),
    end_time: t("end_time"),
    close: t("close"),
    add_new_users:t("add_new_users"),
    save_all:t("save_all"),
    edit_user: t("edit_user"),
    no_hobby_found:t("no_hobby_found"),
    role:t("role"),
    status:t("status"),
    user:t("user"),
    select_role:t("select_role"),
    employee:t("employee"),
    admin:t("admin"),
    edit_employee:t("edit_employee"),
    action_allowed:t("action_allowed"),
    age:t("age"),
    salary:t("salary"),
    dob:t("dob"),
    edit_nested_details:t("edit_nested_details"),
    date_of_birth:t("date_of_birth"),
    start_date:t("start_date"),
    end_date:t("end-date"),
    ok:t("ok"),
    local_time:t("local_time"),
    select_timezone:t("select_timezone"),
    start:t("start"),
    end:t("end"),
    layer_default: t("layer_default"),
    layer_google_normal: t("layer_google_normal"),
    layer_dark: t("layer_dark"),
    layer_light: t("layer_light"),
    layer_topographic: t("layer_topographic"),
    layer_google_satellite: t("layer_google_satellite"),
    layer_google_hybrid: t("layer_google_hybrid"),
    layer_google_terrain: t("layer_google_terrain"),
    choosing_starting_point:t("choosing_starting_point"),
    choose_destination:t("choose_destination"),
    show_path:t("show_path"),
    copied:t("copied"),
    copy_link:t("copy_link"),
    loading_image:t("loading_image"),
    no_image_available:t("no_image_available")

  };
};
