export const HOBBY_OPTIONS = [
  "Reading",
  "Gardening",
  "Brain Games",
  "Playing with Pet",
  "Sleeping",
  "Swimming",
  "Cooking",
  "Baking",
  "Painting",
  "Drawing",
  "Sketching",
  "Writing",
  "Blogging",
  "Photography",
  "Videography",
  "Graphic Design",
  "Singing",
  "Dancing",
  "Playing Guitar",
  "Playing Piano",
  "Playing Violin",
  "Listening to Music",
  "Traveling",
  "Hiking",
  "Camping",
  "Cycling",
  "Running",
  "Jogging",
  "Yoga",
  "Meditation",
  "Gym Workout",
  "Martial Arts",
  "Chess",
  "Board Games",
  "Card Games",
  "Collecting Coins",
  "Collecting Stamps",
  "Collecting Toys",
  "Bird Watching",
  "Fishing",
  "Knitting",
  "Sewing",
  "Embroidery",
  "Woodworking",
  "Pottery",
  "Calligraphy",
  "Origami",
  "DIY Crafts",
  "Home Decor",
  "Makeup",
  "Nail Art",
  "Fashion Styling",
  "Shopping",
  "Learning Languages",
  "Public Speaking",
  "Acting",
  "Podcasting",
  "Watching Movies",
  "Watching TV Shows",
  "Watching Anime",
  "Gaming",
  "Esports",
  "Programming",
  "Web Development",
  "App Development",
  "Robotics",
  "Astronomy",
  "Astrology",
  "Volunteering",
  "Charity Work",
  "Cooking New Recipes",
  "Baking Cakes",
  "Carpentry",
  "Interior Design",
  "Plant Care",
  "Tea Tasting",
  "Coffee Brewing",
  "Travel Planning",
  "Scrapbooking",
  "Journaling",
  "Poetry",
  "Learning Instruments",
  "Pet Training",
  "Aquarium Keeping",
  "Fitness Training",
  "Boxing",
  "Badminton",
  "Table Tennis",
  "Cricket",
  "Football",
  "Basketball",
  "Tennis",
  "Squash",
  "Skating",
  "Skiing",
  "Surfing",
  "Horse Riding",
  "Drone Flying"
] as const;

export type HobbyOption = (typeof HOBBY_OPTIONS)[number];
